name: Create Hugging Face Space

on:
  push:
    branches:
      - '**'  # Triggers on push to any branch

jobs:
  create-hf-space:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
        lfs: true

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install Dependencies
      run: |
        pip install huggingface_hub

    - name: Construct Space Name
      id: vars
      shell: bash
      run: |
        # Extract the repository name (without owner)
        REPO_NAME=$(basename "$GITHUB_REPOSITORY")
        # Extract the branch name
        BRANCH_NAME=$(echo "${GITHUB_REF##*/}")
        # Clean up branch name to be URL-friendly
        BRANCH_NAME_CLEAN=$(echo "$BRANCH_NAME" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g')
        # Construct the space name
        SPACE_NAME="${REPO_NAME}-${BRANCH_NAME_CLEAN}"
        echo "space_name=${SPACE_NAME}" >> $GITHUB_OUTPUT
        echo "branch_name_clean=${BRANCH_NAME_CLEAN}" >> $GITHUB_OUTPUT

    - name: Run hf_space_manager Script
      env:
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
        HF_USERNAME: ${{ secrets.HF_USERNAME }}
      run: |
        python hf_space_manager.py --token ${{ secrets.HF_TOKEN }} --space-name "${{ steps.vars.outputs.space_name }}" --sdk docker --private
        python create_readme.py --title "${{ steps.vars.outputs.space_name }}" --sdk docker --python_version 3.12 --app_file app.py --suggested_hardware basic --app_port 7860

    - name: Push to Hugging Face Space
      env:
        HF_USERNAME: ${{ secrets.HF_USERNAME }}
        HF_TOKEN: ${{ secrets.HF_TOKEN }}
        GIT_EMAIL: ${{ secrets.GIT_EMAIL }}
        GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
        SPACE_NAME: ${{ steps.vars.outputs.space_name }}
        BRANCH_NAME_CLEAN: ${{ steps.vars.outputs.branch_name_clean }}
      run: |
        # Configure Git
        git config --global user.email "${GIT_EMAIL}"
        git config --global user.name "${GIT_USERNAME}"

        # Set up Hugging Face repository URL
        HF_REPO_URL="https://huggingface.co/spaces/${HF_USERNAME}/${SPACE_NAME}.git"

        # Add Hugging Face repository as a remote named 'huggingface'
        git remote add space "$HF_REPO_URL"

        # Set up authentication for Hugging Face
        git config --global credential.helper store
        echo "https://${HF_USERNAME}:${HF_TOKEN}@huggingface.co" > ~/.git-credentials

        git add .
        git commit -m "README.md Created & Pushed to Hugginface Space"

        # Push code to Hugging Face Space's main branch
        git push --force space ${BRANCH_NAME_CLEAN}:main

